"""vote added

Revision ID: 3548c9571aed
Revises: fddfe76a1008
Create Date: 2021-08-18 23:38:42.913417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3548c9571aed'
down_revision = 'fddfe76a1008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('ballotGuid', sa.String(length=36), nullable=False),
    sa.Column('electionOfficialJmbg', sa.String(length=13), nullable=False),
    sa.Column('pollNumber', sa.Integer(), nullable=False),
    sa.Column('electionId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['electionId'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('ballotGuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    # ### end Alembic commands ###
