"""id in votes

Revision ID: 84248d526888
Revises: 3548c9571aed
Create Date: 2021-08-20 12:04:26.119631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84248d526888'
down_revision = '3548c9571aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'id')
    # ### end Alembic commands ###
