"""vote added

Revision ID: d3337c059878
Revises: 84248d526888
Create Date: 2021-08-20 12:07:17.736606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3337c059878'
down_revision = '84248d526888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ballotGuid', sa.String(length=36), nullable=False),
    sa.Column('electionOfficialJmbg', sa.String(length=13), nullable=False),
    sa.Column('pollNumber', sa.Integer(), nullable=False),
    sa.Column('electionId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['electionId'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    # ### end Alembic commands ###
