version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
    - authenticationData:/var/lib/mysql
    networks:
      - mynet
  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      authenticationDB:
        condition: service_healthy
    networks:
      - mynet
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      - authenticationDBMigration
    ports:
    - 5002:5002
    networks:
      - mynet
  redis:
    image: redis
    ports:
    - 6379:6379
    networks:
      - mynet
  electionsDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
    - electionsData:/var/lib/mysql
    networks:
      - mynet
  electionsDBMigration:
    image: electionsdbmigration
    environment:
      - DATABASE_URL=electionsDB
    depends_on:
      electionsDB:
        condition: service_healthy
    networks:
      - mynet
  admin:
    image: admin
    environment:
      - DATABASE_URL=electionsDB
    ports:
    - 5001:5001
    networks:
      - mynet
  user:
    image: user
    environment:
      - DATABASE_URL=electionsDB
    depends_on:
      - electionsDBMigration
      - redis
    ports:
    - 5003:5003
    networks:
      - mynet
#    deploy:
#      mode: replicated
#      replicas: 3
  daemon:
    image: daemon
    environment:
      - DATABASE_URL=electionsDB
    depends_on:
      - electionsDBMigration
      - user
      - redis
    networks:
      - mynet
  adminer:
    image: adminer
    depends_on:
      - authenticationDBMigration
      - electionsDBMigration
    ports:
    - 8080:8080
    networks:
      - mynet

volumes:
  authenticationData:
  electionsData:
networks:
  mynet: